adapters:
  openai: OpenAIAdapter

llms:
  siliconflow:
    adapter: openai
    url: https://api.siliconflow.cn/v1
    api_key: "${SILICONFLOW_API_KEY}"
    default_model: deepseek-ai/DeepSeek-V2.5

default_llm: siliconflow
template_path: "./templates"
worker_path: "./workers"
logger_file: "./logs/ruby_gen_cli.log"